name: Docker Image of jenkins with aws-cdk

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_HUB_ID}}
          DOCKER_PWD: ${{secrets.DOCKER_HUB_PWD}}
        run: |
          echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_ID}}/jenkins-lts-with-aws-cdk:lts

      - name:  Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{secrets.DOCKER_HUB_ID}}/jenkins-lts-with-aws-cdk:lts

