name: Docker Image of jenkins with aws-cdk

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_HUB_ID}}
          DOCKER_PWD: ${{secrets.DOCKER_HUB_PWD}}
        run: |
          echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_ID}}/jenkins-lts-with-aws-cdk:lts

      - name: Docker Push
          run: docker push ${{secrets.DOCKER_HUB_ID}}/jenkins-lts-with-aws-cdk:lts


